package com.cmsz.cmup.commons.logging.mapper;

import com.cmsz.cmup.commons.logging.mapper.AlarmLogBean;
import com.cmsz.cmup.commons.logging.mapper.AlarmLogBeanExample;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

/**
 * 通用业务告警日志mapper接口类
 * generated by MyBatis Generator
 *
 * @author JinChao
 * 
 * @date 2015年12月16日 下午4:23:36
 *
 */
public interface AlarmLogBeanMapper {
	
	/**
     * 根据系统名称查告警日志
     *
     * @mbggenerated
     */
    List<AlarmLogBean> selectBySystem(String System);
    
    /**
     * 根据日志级别查告警日志
     *
     * @mbggenerated
     */
    List<AlarmLogBean> selectByLevels(int levels);
    
    /**
     * 根据业务线查告警日志
     *
     * @mbggenerated
     */
    List<AlarmLogBean> selectByBusinessline(String businessline);
    
    /**
     * 根据province查告警日志
     *
     * @mbggenerated
     */
    List<AlarmLogBean> selectByProvince(String province);
    
    /**
     * 根据ip查告警日志
     *
     * @mbggenerated
     */
    List<AlarmLogBean> selectByIp(String ip);
    
    
    /**
     * 根据时间的查询查告警日志
     * 时间格式:2015-12-14 15:47:05
     * @param startTime 起始时间,格式如:"2015-12-14 15:47:05"
     * @param endTime 结束时间,格式如:"2015-12-14 15:47:05"
     * @mbggenerated
     */
    List<AlarmLogBean> selectByTime(String startTime,String endTime);
    
    /**
     * 根据AlarmLogBean的属性查询
     * <p>paramsMap支持的属性值有:1.system,2businessline,3.levels,4.province</p>
     * <p>5.ip,6.startTime 起始时间,格式如:"2015-12-14 15:47:05",7.endTime 结束时间,格式如:"2015-12-14 15:47:05"</p>
     * @param paramsMap,
     * @mbggenerated
     */
    List<AlarmLogBean> selectByParams(@Param(value = "params")Map<String, String> paramsMap);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_ALARM
     *
     * @mbggenerated
     */
    int countByExample(AlarmLogBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_ALARM
     *
     * @mbggenerated
     */
    int deleteByExample(AlarmLogBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_ALARM
     *
     * @mbggenerated
     */
    int insert(AlarmLogBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_ALARM
     *
     * @mbggenerated
     */
    int insertSelective(AlarmLogBean record);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_ALARM
     *
     * @mbggenerated
     */
    List<AlarmLogBean> selectByExample(AlarmLogBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_ALARM
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AlarmLogBean record, @Param("example") AlarmLogBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOG_ALARM
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AlarmLogBean record, @Param("example") AlarmLogBeanExample example);
}